// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)

import HomeController from "./home_controller.js"
application.register("home", HomeController)

import HomeSearchController from "./home_search_controller.js"
application.register("home-search", HomeSearchController)

import ListingFormController from "./listing_form_controller.js"
application.register("listing-form", ListingFormController)

import LoginController from "./login_controller.js"
application.register("login", LoginController)
import AddressAutocompleteController from "./address_autocomplete_controller.js"
application.register("address-autocomplete", AddressAutocompleteController)

import CheckoutController from "./checkout_controller"
application.register("checkout", CheckoutController)

