name: snoofly-minio

networks:
  snoofly-net:
    external: true

services:
  minio-snoofly:
    image: minio/minio:latest   # <-- use a valid tag
    container_name: minio-snoofly
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    # Only expose the console; keep S3 API internal to the snoofly-net
    ports:
      - "9001:9001" # optional; remove if you’ll use it only via the network
    volumes:
      - minio_data:/data
    networks: [snoofly-net]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001/minio/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 12

volumes:
  minio_data: