version: '3.8'

services:
  caddy:
    image: caddy:2
    container_name: caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - snoofly-net

  web:
    build: .
    command: >
      bash -c "rm -f tmp/pids/server.pid &&
               bin/rails assets:precompile &&
               bin/rails s -p 3000 -b '0.0.0.0'"
    restart: always
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    env_file:
      - .env
    environment:
      - RAILS_ENV=${RAILS_ENV}
      - RAILS_LOG_TO_STDOUT=true
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME_DEV=${DB_NAME_DEV}
      - DB_NAME_PROD=${DB_NAME_PROD}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
    networks:
      - snoofly-net

networks:
  snoofly-net:
    external: true

volumes:
  bundle:
  caddy_data:
  caddy_config: