version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        # Needed if you precompile assets in Dockerfile.prod
        SECRET_KEY_BASE: ${SECRET_KEY_BASE}
        RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
    container_name: web-1
    restart: unless-stopped
    env_file:
      - .env
    environment:
      RAILS_ENV: production
      RAILS_LOG_TO_STDOUT: "1"
      RAILS_SERVE_STATIC_FILES: "1"
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME_PROD: ${DB_NAME_PROD}
      SECRET_KEY_BASE: ${SECRET_KEY_BASE}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      # Add any others you need at runtime (REDIS_URL, S3/MinIO, etc.)
    expose:
      - "3000"
    networks:
      - snoofly-net
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:3000/ || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 10

  caddy:
    image: caddy:2
    container_name: caddy
    restart: unless-stopped
    depends_on:
      web:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile.prod:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - snoofly-net

networks:
  snoofly-net:
    external: true

volumes:
  caddy_data:
  caddy_config: