version: "3.9"

name: snoofly-minio

networks:
  snoofly-net:
    external: true

services:
  minio-snoofly:
    image: minio/minio:RELEASE.2024-09-01T00-00-00Z
    container_name: minio-snoofly
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    ports:
      - "9001:9001"   # Console (optional to expose)
      # Do NOT expose 9000 publicly if you prefer internal-only access
    volumes:
      - minio_data:/data
    networks: [snoofly-net]

volumes:
  minio_data: