name: snoofly-mail

networks:
  snoofly-net:
    external: true

volumes:
  maildata:
  mailstate:
  maillogs:
  roundcube_data:
  caddy_data:
    external: true
    name: shoofly-properties_caddy_data   # <- matches your running Caddy volume

services:
  mail:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mail
    hostname: mail
    domainname: snoofly.co.uk
    restart: unless-stopped
    env_file:
      - .env
    environment:
      ENABLE_SPAMASSASSIN: "0"
      ENABLE_CLAMAV: "0"
      ENABLE_FAIL2BAN: "1"
      ENABLE_POSTGREY: "0"
      ONE_DIR: "1"
      PERMIT_DOCKER: "network"
      TLS_LEVEL: "modern"

      # Certs issued by Caddy for mail.snoofly.co.uk
      # NOTE: Caddy stores under /data/caddy/certificates/...; we mount that at /mnt/caddy
      environment:
      SSL_TYPE: "manual"
      SSL_CERT_PATH: "/mnt/caddy/caddy/certificates/acme-v02.api.letsencrypt.org-directory/mail.snoofly.co.uk/mail.snoofly.co.uk.crt"
      SSL_KEY_PATH:  "/mnt/caddy/caddy/certificates/acme-v02.api.letsencrypt.org-directory/mail.snoofly.co.uk/mail.snoofly.co.uk.key"

      # We read mail locally; outbound sending stays with SendGrid
      RELAY_HOST: ""
      SMTP_ONLY: "0"
      ENABLE_OPENDKIM: "1"
    ports:
      - "25:25"    # SMTP in
      - "993:993"  # IMAPS
      - "587:587" 
      - "465:465"
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    stop_grace_period: 1m
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./docker-mailserver/config/:/tmp/docker-mailserver/
      - caddy_data:/mnt/caddy:ro
    networks: [snoofly-net]
    healthcheck:
      test: ["CMD-SHELL", "timeout 3 bash -lc '</dev/tcp/127.0.0.1/25' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10

  roundcube:
    image: roundcube/roundcubemail:latest
    container_name: roundcube
    restart: unless-stopped
    depends_on:
      - mail
    environment:
      # IMAP (read mail from docker-mailserver)
      ROUNDCUBE_DEFAULT_HOST: "ssl://mail.snoofly.co.uk"
      ROUNDCUBE_DEFAULT_PORT: "993"

      # SMTP (send via SendGrid)
      ROUNDCUBE_SMTP_SERVER: "smtp.sendgrid.net"
      ROUNDCUBE_SMTP_PORT: "587"
      ROUNDCUBE_SMTP_USER: "apikey"                # literal username for SendGrid
      ROUNDCUBE_SMTP_PASS: "${SENDGRID_API_KEY}"   # set in .env
      ROUNDCUBE_SMTP_AUTH_TYPE: "LOGIN"
      ROUNDCUBE_SMTP_AUTH: "true"

      ROUNDCUBE_DES_KEY: "${ROUNDCUBE_DES_KEY:-change-me-24-chars}"
      ROUNDCUBE_PLUGINS: "archive,zipdownload,managesieve,markasjunk"
      UPLOAD_MAX_FILESIZE: "25M"
      MEMORY_LIMIT: "256M"
    volumes:
      - roundcube_data:/var/roundcube
    expose:
      - "80"
    networks: [snoofly-net]
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost/ >/dev/null 2>&1 || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 10