name: snoofly-minio

networks:
  snoofly-net:
    external: true

volumes:
  minio_data:

services:
  minio-snoofly:
    image: minio/minio:latest
    container_name: minio-snoofly
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      # Let MinIO embed correct host in presigned URLs
      MINIO_SERVER_URL: https://s3.snoofly.co.uk
      # Optional, but nice to be explicit
      MINIO_REGION: us-east-1
      # If you want console through HTTPS proxy too:
      MINIO_BROWSER_REDIRECT_URL: https://minio-console.snoofly.co.uk
    volumes:
      - minio_data:/data
    expose:
      - "9000"   # S3 API (proxied by Caddy)
      - "9001"   # Console (proxied by Caddy if you set it up)
    networks: [snoofly-net]
    healthcheck:
      test: ["CMD", "curl", "-sf", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 3s
      retries: 10

  minio-mc-init:
    image: minio/mc:latest
    container_name: minio-mc-init
    depends_on:
      minio-snoofly:
        condition: service_healthy
    entrypoint: ["/bin/sh","-c"]
    command: >
      set -e
      mc alias set myminio http://minio-snoofly:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};

      # Create bucket if missing
      mc ls myminio/${MINIO_BUCKET} >/dev/null 2>&1 || mc mb --region=${MINIO_REGION:-us-east-1} myminio/${MINIO_BUCKET};

      # Keep bucket PRIVATE (Active Storage uses presigned URLs)
      mc anonymous set none myminio/${MINIO_BUCKET};

      # CORS so browsers can GET the presigned URLs and PUT (if you ever use direct uploads)
      cat >/tmp/cors.json <<'JSON'
      [
        {
          "AllowedOrigin": [
            "https://snoofly.co.uk",
            "https://www.snoofly.co.uk",
            "https://s3.snoofly.co.uk",
            "http://localhost:3000",
            "http://app.localhost"
          ],
          "AllowedMethod": ["GET","PUT","POST","DELETE"],
          "AllowedHeader": ["*"],
          "ExposeHeader": ["ETag","Location"],
          "MaxAgeSeconds": 3000
        }
      ]
      JSON
      mc cors set myminio/${MINIO_BUCKET} /tmp/cors.json;

      echo 'MinIO init done.';
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_BUCKET: ${MINIO_BUCKET}
      MINIO_REGION: ${MINIO_REGION:-us-east-1}
    networks: [snoofly-net]
    restart: "no"