version: "3.9"

services:
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails s -p 3000 -b 0.0.0.0"
    volumes:
      - .:/usr/src/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      RAILS_ENV: development
      RACK_ENV: development
      # Nice logs in containers
      RAILS_LOG_TO_STDOUT: "1"
      # History file inside container
      HISTFILE: /usr/src/app/log/.bash_history
      # Service endpoints (service names = hosts)
      DB_HOST: db
      REDIS_URL: redis://redis:6379/1
      ACTION_CABLE_URL: ws://localhost:3000/cable
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: snoofly_development
    # Uncomment if you need to connect from host tools (psql, TablePlus)
    # ports:
    #   - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes", "--save", "60", "1", "--loglevel", "warning"]
    # Uncomment if you need to inspect from host (redis-cli on host)
    # ports:
    #   - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  pg_data:
  redis_data:
  bundle: