version: "3.9"

name: snoofly-sidekiq

networks:
  snoofly-net:
    external: true

services:
  sidekiq-snoofly:
    image: your-registry/snoofly-web:latest   # same image as web (has app code)
    container_name: sidekiq-snoofly
    restart: unless-stopped
    env_file:
      - .env.production
    environment:
      RAILS_ENV: production
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
      DB_HOST: db-snoofly
      DB_PORT: 5432
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME_PROD: ${DB_NAME_PROD}
      REDIS_URL: redis://redis-snoofly:6379/1
    command: bash -lc "bundle exec sidekiq -C config/sidekiq.yml"
    networks: [snoofly-net]
    depends_on:
      - db-snoofly
      - redis-snoofly