default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("DB_HOST") { "db-snoofly" } %>
  port: <%= ENV.fetch("DB_PORT") { 5432 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "postgres" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "" } %>

development:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_DEV") { "snoofly_development" } %>

test:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_TEST") { "snoofly_test" } %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME_PROD") { "snoofly_production" } %>